# Generated by Django 4.1.6 on 2023-04-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_prod_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_descp',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_descp_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_descp_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_descp_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_descp_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_descp_5',
            field=models.TextField(blank=True),
        ),
    ]
