# Generated by Django 4.1.6 on 2023-04-03 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_prod_descp_product_prod_descp_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_descp_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_descp_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_descp_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_descp_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_descp_5',
        ),
        migrations.CreateModel(
            name='Product_Description',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('prod_descp', models.TextField(blank=True)),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
