# Generated by Django 4.1.6 on 2023-05-20 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_prod_descp_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 20, 18, 26, 7, 531506))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
