# Generated by Django 4.1.6 on 2023-05-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_reviews_publish_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
