# Generated by Django 4.1.6 on 2023-05-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 20, 20, 24, 30, 328721)),
        ),
    ]
