# Generated by Django 4.1.6 on 2023-04-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_razorpay_order_id_cart_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_done_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
