# Generated by Django 4.1.6 on 2023-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_payment_done_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
