# Generated by Django 4.1.6 on 2023-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cart_cart_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cv_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
