# Generated by Django 4.1.6 on 2023-05-21 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 22, 2, 59, 585439)),
        ),
    ]
