# Generated by Django 4.1.6 on 2023-05-24 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_cart_publish_date_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid_cart_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 19, 51, 19, 66294)),
        ),
    ]
