# Generated by Django 4.1.6 on 2023-06-01 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cart_paid_cart_quantity_alter_cart_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 2, 0, 10, 44, 265517)),
        ),
    ]
