# Generated by Django 4.1.6 on 2023-06-01 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_myorders_invoice_no_alter_cart_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='invoice_no',
        ),
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 2, 0, 59, 52, 149260)),
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('my_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_order', to='accounts.myorders')),
            ],
        ),
    ]
