# Generated by Django 4.1.6 on 2023-06-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_myorders_invoice_no_alter_cart_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 2, 1, 4, 25, 89196)),
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
